#! /usr/bin/env ruby

require 'byebug' # DELETE ME
require './lib/user.rb'
require './lib/gist.rb'
require './lib/task.rb'
require './lib/report.rb'
require './lib/report_api.rb'

def show_usage_message(exit_status = 0)
	puts "Use `report` as follows:\n\n"
	puts "\t`report start TASK-DESCRIPTION`"
	puts "\t\t- finds or create a new gist for today"
	puts "\t\t- adds a new item with the provided TASK-DESCRIPTION\n\n"
	puts "\t`report list`"
	puts "\t\t- Lists all the tasks from today, including their TASK-ID\n\n"
	puts "\t`report stop`"
	puts "\t\t- stops time tracking the current task, if it exists\n\n"
	puts "\t`report continue [TASK-ID]`"
	puts "\t\t- continues time tracking the latest task, if it exists\n\n"
	puts "\t`report help`"
	puts "\t\t- shows this message"

	exit exit_status
end

User.name = 'mpataki' # TODO: pull this from a config (maybe even .git_config ?)
User.api_token = File.read('gist_token').strip

begin
	case ARGV[0]
	when 'list'
		# TODO: list today's items
		puts "Not Implemented\n\n"
		puts "\t- Lists all the tasks from today, including their TASK-ID"
		exit
	when 'start'
		ReportAPI.start(ARGV[0])
	when 'stop'
		ReportAPI.stop
	when 'continue'
		ReportAPI.continue(ARGV[1])
	# when 'delete'
	# when 'info'
	else
		show_usage_message
	end
rescue Report::TaskAlreadyTracked
	puts "Task '#{ARGV[0]}' is already being tracked. Continuing the task."
	ARGV[1] = ARGV[0]
	ARGV[0] = 'continue'
	retry
end
